name: phyche
description: A new Flutter project.

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17
  google_fonts: ^4.0.3
  provider: ^6.0.5
  flutter_svg_provider: ^1.0.3
  flutter_rating_bar: ^4.0.1
  video_player: ^2.2.18
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^4.0.4
  cached_network_image: ^3.2.3
  path_provider: ^2.0.14
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  fluttertoast: ^8.0.8
  cloud_firestore: ^4.5.0
  flutter_chat_ui: ^1.6.6
  open_filex: ^4.3.2
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  mime: ^1.0.2
  uuid: ^3.0.6
  file_picker: ^5.2.2
  firebase_storage: ^11.0.3
  flutter_firebase_chat_core: ^1.6.4
  url_launcher: ^6.0.3
  google_ml_kit: ^0.13.0


dev_dependencies:
  build_runner: ^2.3.3
  built_value_generator: ^8.4.4

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/image/
    - asset/icons/

